### ISSUE TITLE
need to set conda to shell after exec

### ISSUE THREAD

**Issue by Aciole-David** [menegidio-lab/entap-docker#2]
root@b57d17bb87a2:/# conda activate base

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

**Comment by menegidio-lab** [comment]
Close
