### ISSUE TITLE
please, add tree

### ISSUE THREAD

**Issue by Aciole-David** [menegidio-lab/entap-docker#4]
please, add "tree" command ready-to-use, like

 #preferably
conda install -c conda-forge tree

#or maybe
 yum install tree	 #RHEL/CentOS 7
 dnf install tree	 #Fedora 22+ and /RHEL/CentOS 8
 sudo apt install tree	 #Ubuntu/Debian
 sudo zypper in tree 	 #openSUSE

**Comment by menegidio-lab** [comment]
Close
